FROM node:12.1

RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Make yarn available to SH, and thus your compose file
ENV PATH="/root/.yarn/bin:${PATH}"

# Create app directory
RUN mkdir -p /src/app
WORKDIR /src/app

# to make npm test run only once non-interactively
ENV CI=true

# Install app dependencies
COPY package.json /src/app/
RUN yarn

# Bundle app source
COPY . /src/app

EXPOSE 3010
EXPOSE 35729

# defined in package.json
CMD [ "yarn", "start" ]
